export const placeHoldersNames = {
  firstName:"First Name",
  LastName:"Enter Last Name",
  Email:"Enter Email",
  MobileNumber:"Mobile Number",
  WriteYourQuery:"Write Your Query",
  Name:"Enter Your Name",
  SupplementaryCard:"Enter Supplementary Card",
  Address:"Enter Your Address",
  Verification:"Varification Status",
  Number:"2000",
  BusinessName:"Business Name",
  Age:"Enter Your Age",
  EIDA:"Enter Your EIDA No.",
  PassportNumber:"Enter Your Passport Number",
  ResidenceVintage:"Enter Your Residence Vintage",
  DependentsNumber:"Enter The Number of Dependents",
  VisaNumber:"Enter Visa Number",
  EmployerName:"Enter Employer Name",
  BankingCode:"Enter Banking Code",
  TotalExperience:"Enter Total Experience(months)",
  BankName:"Enter Bank Name",
  AccountNumber:"Enter Account Number"

}