import { borderWidth, fontSize, fontWeight, radius, spacing } from "@/constants/Metrics";
import { Dimensions, StyleSheet } from "react-native";
const { width } = Dimensions.get("window");
export const localStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "white" },
  bottomNav: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderTopWidth: borderWidth.thin,
    backgroundColor: "white",
    paddingBottom: spacing.sm,
    paddingTop: spacing.sm,
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  navIcon: { width: 22, height: 22, marginBottom: spacing.xs },
  navText: { fontSize: fontSize.xxs, fontWeight: fontWeight.medium },
  activeUnderline: {
    position: "absolute",
    bottom: 0,
    height: 2,
    width: "40%",
    borderRadius: radius.sm,
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    marginTop: spacing.md,
  },
  avatar: { width: 50, height: 50, borderRadius: radius.xxxl, marginRight: 12 },
  welcome: { fontSize: 14 },
  username: { fontSize: fontSize.lg, fontWeight: fontWeight.normal },
  banner: {
    margin: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    overflow: "hidden",
  },
  bannerText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    padding: 10,
    borderRadius: 8,
  },
  bannerImage: { width: 100, height: 100, borderRadius: 12, marginLeft: 12 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 16,
    marginBottom: 10,
    justifyContent:"flex-start",
    gap:spacing.sm
  },
  serviceRow: {
    width: 124,
    height: 118,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    gap: spacing.md, 
  },
  serviceCard: {
    borderRadius: 12,
    width: 100,
    height: 80,
    justifyContent: "center",
    alignItems: "center",
  },
  serviceIcon: { fontSize: 20, marginBottom: 5 },
  serviceText: { fontSize: 14, fontWeight: "600" },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginTop: 20,
  },
  applyCard: {
    width: (width - 48) / 2,
    height: 140,
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 16,
    position: "relative",
  },
  applyImage: { width: "100%", height: "100%" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  applyText: {
    position: "absolute",
    bottom: 10,
    left: 10,
    fontSize: 16,
    fontWeight: "700",
  },
});
